services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'    # RabbitMQ broker port (AMQP)
      - '15672:15672'  # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'

volumes:
  redis_data: